logging:
  config: classpath:logback.xml
server:
  port: 8701
xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:8700/xxl-job-admin
    executor:
      address: ''
      appname: xxl-job-executor-sample
      ip: ''
      logpath: data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999
spring:
  mqtt:
    username: zhangxin
    password: 123
    #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://10.241.11.106:61613，tcp://192.168.2.133:61613
    url: tcp://10.241.11.106:61613
#    url: ${mqtt.url}
    #MQTT-连接服务器默认客户端ID
    clientId: arcbase4view
#    clientId: ${random.value}
    #MQTT-默认的消息推送主题，实际可在调用接口时指定
    defaultTopic: thing/115580863084822555/device/+/post
    completionTimeout: 10
arc:
  os:
    tenantId: 174421788237759014

